import { AggregationMethod } from '../client/publicClient/dimension';

export const input = [
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['1', '2'], aggregatedValue: '3' },
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['0', '0'], aggregatedValue: '0' },
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['-1', '-2'], aggregatedValue: '-3' },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '10',
    },
    { aggregationMethod: AggregationMethod.Sum, usageInput: ['1000000', '2000000'], aggregatedValue: '3000000' },
    {
        aggregationMethod: AggregationMethod.Sum,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '30000000000',
    },
    { aggregationMethod: AggregationMethod.Average, usageInput: ['1', '2'], aggregatedValue: '1.5' },
    { aggregationMethod: AggregationMethod.Average, usageInput: ['0', '0'], aggregatedValue: '0' },
    { aggregationMethod: AggregationMethod.Average, usageInput: ['-1', '-2'], aggregatedValue: '-1.5' },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
    },
    { aggregationMethod: AggregationMethod.Average, usageInput: ['1000000', '2000000'], aggregatedValue: '1500000' },
    {
        aggregationMethod: AggregationMethod.Average,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '15000000000',
    },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['1', '2'], aggregatedValue: '1' },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['0', '0'], aggregatedValue: '0' },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['-1', '-2'], aggregatedValue: '-2' },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
    },
    { aggregationMethod: AggregationMethod.Min, usageInput: ['1000000', '2000000'], aggregatedValue: '1000000' },
    {
        aggregationMethod: AggregationMethod.Min,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '10000000000',
    },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['1', '2'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['0', '0'], aggregatedValue: '0' },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['-1', '-2'], aggregatedValue: '-1' },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '1',
    },
    { aggregationMethod: AggregationMethod.Max, usageInput: ['1000000', '2000000'], aggregatedValue: '2000000' },
    {
        aggregationMethod: AggregationMethod.Max,
        usageInput: ['10000000000', '20000000000'],
        aggregatedValue: '20000000000',
    },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['1', '2'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['0', '0'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['-1', '-2'], aggregatedValue: '2' },
    {
        aggregationMethod: AggregationMethod.Count,
        usageInput: ['1', '1', '1', '1', '1', '1', '1', '1', '1', '1'],
        aggregatedValue: '10',
    },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['1000000', '2000000'], aggregatedValue: '2' },
    { aggregationMethod: AggregationMethod.Count, usageInput: ['10000000000', '20000000000'], aggregatedValue: '2' },
];
