export default {
    resource: '/invoice',
    path: '/invoice',
    httpMethod: 'POST',
    headers: {
        Accept: '*/*',
        'Accept-Encoding': 'gzip, deflate, br',
        'Cache-Control': 'no-cache',
        'Content-Type': 'text/plain',
        Host: '2x1zjgsudi.execute-api.us-east-1.amazonaws.com',
        id: 'foobar',
        'Postman-Token': '2e658d19-8980-4e29-9176-279531aa5990',
        'User-Agent': 'PostmanRuntime/7.28.4',
        'X-Amzn-Trace-Id': 'Root=1-61b50e65-3cd497383bd6a1e75e771d24',
        'X-Forwarded-For': '54.86.50.139',
        'X-Forwarded-Port': '443',
        'X-Forwarded-Proto': 'https',
    },
    multiValueHeaders: {
        Accept: ['*/*'],
        'Accept-Encoding': ['gzip, deflate, br'],
        'Cache-Control': ['no-cache'],
        'Content-Type': ['text/plain'],
        Host: ['2x1zjgsudi.execute-api.us-east-1.amazonaws.com'],
        id: ['foobar'],
        'Postman-Token': ['2e658d19-8980-4e29-9176-279531aa5990'],
        'User-Agent': ['PostmanRuntime/7.28.4'],
        'X-Amzn-Trace-Id': ['Root=1-61b50e65-3cd497383bd6a1e75e771d24'],
        'X-Forwarded-For': ['54.86.50.139'],
        'X-Forwarded-Port': ['443'],
        'X-Forwarded-Proto': ['https'],
    },
    queryStringParameters: 'None',
    multiValueQueryStringParameters: 'None',
    pathParameters: 'None',
    stageVariables: 'None',
    requestContext: {
        resourceId: 'il6ac9',
        resourcePath: '/metrics',
        operationName: 'addMetrics',
        httpMethod: 'POST',
        extendedRequestId: 'KM8v5FskoAMFiuA=',
        requestTime: '11/Dec/2021:20:47:33 +0000',
        path: '/dev/metrics',
        accountId: '839145551229',
        protocol: 'HTTP/1.1',
        stage: 'dev',
        domainPrefix: '2x1zjgsudi',
        requestTimeEpoch: 1639255653500,
        requestId: '3311048b-a304-4377-8a9a-f256acc52f7c',
        identity: {
            cognitoIdentityPoolId: 'None',
            accountId: 'None',
            cognitoIdentityId: 'None',
            caller: 'None',
            sourceIp: '54.86.50.139',
            principalOrgId: 'None',
            accessKey: 'None',
            cognitoAuthenticationType: 'None',
            cognitoAuthenticationProvider: 'None',
            userArn: 'None',
            userAgent: 'PostmanRuntime/7.28.4',
            user: 'None',
        },
        domainName: '2x1zjgsudi.execute-api.us-east-1.amazonaws.com',
        apiId: '2x1zjgsudi',
    },
    body: JSON.stringify({
        startDate: '2022-05-01T00:12:00.000Z',
        endDate: '2022-05-08T00:12:00.000Z',
        saasBusinessId: 'MyCorpName',
        customerId: 'MyClient',
    }),
    isBase64Encoded: 'false',
};
